substitutions:
  name: bedroom-ac
  friendly_name: Bedroom Climate
  #follow_me_sensor: sensor.bedroom_temperature

esphome:
  project:
    name: "dudanov.electrolux-ac-control"
    version: "1.0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Must be used once. It is necessary to comment out after the first firmware update.
  use_address: iot-uni-dongle.local

packages:
  remote_package:
    url: https://github.com/dudanov/esphome-packages
    refresh: 0d
    files: [
      # Main dongle package
      hardware/iot-uni-dongle/device.yaml,
      # IR remote transmitter (IR- pad connected to TSOP output of controlled device)
      hardware/iot-uni-dongle/remote/tsop.yaml,
      # IR remote transmitter (IR LED between IR+ and IR- pads)
      #hardware/iot-uni-dongle/remote/led.yaml,
      # Electrolux EACS. Select your model HERE.
      climate/midea/electrolux.yaml,

      # "Flash" button. Run `button_click` script on click.
      hardware/iot-uni-dongle/button.yaml,
      # Toggles power on button click. (Not working yet. Support will be in next ESPHome release 2022.6)
      climate/midea/common/button_action/power.yaml,

      # "Beeper feedback" switch
      climate/midea/common/beeper.yaml,
      # "Display toggle" button. Works only via IR transmitter for Electrolux EACS.
      climate/midea/common/display.yaml,
      # "Swing step" button. Works only via IR transmitter.
      climate/midea/common/swing.yaml,
      # "FollowMe" capability via HomeAssistant service.
      climate/midea/common/follow_me/service.yaml,
      # "FollowMe" capability via HomeAssistant sensor.
      # Sensor entity name setting up via ${follow_me_sensor} substitution.
      #climate/midea/common/follow_me/sensor.yaml,
    ]
